name: mkepost

on:
  schedule:
    - cron: '12,42 * * * *'  # every half hour

jobs:
  mkesurf-post:
    runs-on: macOS-latest
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      MAPBOX_PUBLIC_ACCESS_TOKEN: ${{ secrets.MAPBOX_PUBLIC_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install rtweet package
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE)'
      - name: Install readr package
        run: Rscript -e 'install.packages("readr", dependencies = TRUE)'
      - name: Install lubridate package
        run: Rscript -e 'install.packages("lubridate", dependencies = TRUE)'
      - name: Install lubridate package
        run: Rscript -e 'install.packages("dplyr", dependencies = TRUE)'
         
      - name: Create and post tweet
        run: Rscript noaa-tweet.R
